{% set name = "wield.bunch" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wield.bunch-{{ version }}.tar.gz
  sha256: 855fc2883c0eb14aebefe14c4374e52fdf419870499561cf5c37ad139a58778c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - wield.bunch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wieldphysics/wield-bunch
  summary: bunch container objects like Matlab structs
  license: Apache-2.0
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - mccullerlp 
